// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0BYitqfIJTeJT_PPwrpwryHluwV5hew',
    appId: '1:812177127629:web:18721be73c71acf9e6d184',
    messagingSenderId: '812177127629',
    projectId: 'reddamhouse-afb7a',
    authDomain: 'reddamhouse-afb7a.firebaseapp.com',
    storageBucket: 'reddamhouse-afb7a.appspot.com',
    measurementId: 'G-SJRZB62VYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9I29va00JUeNcNKau8D9o3UtOdI8ln4',
    appId: '1:812177127629:android:04ae8a707fafce72e6d184',
    messagingSenderId: '812177127629',
    projectId: 'reddamhouse-afb7a',
    storageBucket: 'reddamhouse-afb7a.appspot.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvBdZPevvpn26gAlNHepxiVBIqf8qXNM',
    iosBundleId: 'com.example.cceReddamHouse',
    appId: '1:812177127629:ios:09cb827b6104959be6d184',
    storageBucket: 'reddamhouse-afb7a.appspot.com',
    messagingSenderId: '812177127629',
    iosClientId: 'undefined',
    projectId: 'reddamhouse-afb7a'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvBdZPevvpn26gAlNHepxiVBIqf8qXNM',
    appId: '1:812177127629:ios:09cb827b6104959be6d184',
    messagingSenderId: '812177127629',
    projectId: 'reddamhouse-afb7a',
    storageBucket: 'reddamhouse-afb7a.appspot.com',
    iosBundleId: 'com.example.cceReddamHouse',
  );
}
